baseURL = "https://docs.fearthec.io/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo-theme-learn"


[params]
  themeVariant = "learn-ftc"
  author = "Quentin Bonaventure"

[outputs]
  home = [ "HTML", "RSS", "JSON"]


[languages]
  [languages.en]
    title = "FTC Discord Bot documentation"
    weight = 1
    languageName = "English"
    [languages.en.params]
  [languages.fr]
    title = "Documentations FTC Discord Bot"
    weight = 2
    languageName = "Français"
    [languages.fr.params]
      [languages.fr.params.navigation]
        help = "Aide"